### ISSUE TITLE
firefox dependency

### ISSUE THREAD

**Issue by DancingQuanta** [jbaiter/zotero-cli#15]
I found that to use local storage `firefox` is needed.
I suggest a option for the configuration file, a path to the zotero storage.

**Comment by jbaiter** [comment]
Thanks for noticing, that was a bug, fixed with https://github.com/jbaiter/zotero-cli/commit/802c6f821022cc560e5a9d08d68d3b437cd969be
If the application can find neither the Firefox nor the Zotero standalone directories, it will prompt you for the path.
You can also set it explicitely via the `storage_dir` option in your configuration file (~/.config/ztotero-cli/config.ini).
